export const languages = {
  Afrikaans: 'af',
  Akan: 'ak',
  Amharic: 'am',
  Arabic: 'ar',
  'Arabic (U.A.E.)': 'ar-AE',
  'Arabic (Bahrain)': 'ar-BH',
  'Arabic (Algeria)': 'ar-DZ',
  'Arabic (Egypt)': 'ar-EG',
  'Arabic (Iraq)': 'ar-IQ',
  'Arabic (Jordan)': 'ar-JO',
  'Arabic (Kuwait)': 'ar-KW',
  'Arabic (Lebanon)': 'ar-LB',
  'Arabic (Libya)': 'ar-LY',
  'Arabic (Morocco)': 'ar-MA',
  'Arabic (Oman)': 'ar-OM',
  'Arabic (Qatar)': 'ar-QA',
  'Arabic (Saudi Arabia)': 'ar-SA',
  'Arabic (Syria)': 'ar-SY',
  'Arabic (Tunisia)': 'ar-TN',
  'Arabic (Yemen)': 'ar-YE',
  Mapudungun: 'arn',
  Assamese: 'as',
  Azeri: 'az',
  'Azeri (Cyrillic, Azerbaijan)': 'az-Cyrl-AZ',
  'Azeri (Latin, Azerbaijan)': 'az-Latn-AZ',
  Bashkir: 'ba',
  Belarusian: 'be',
  Bulgarian: 'bg',
  Bambara: 'bm',
  Bengali: 'bn',
  'Bengali (Bangladesh)': 'bn-BD',
  'Bengali (India)': 'bn-IN',
  Tibetan: 'bo',
  Breton: 'br',
  Bosnian: 'bs',
  'Bosnian (Cyrillic)': 'bs-Cyrl',
  'Bosnian (Latin)': 'bs-Latn',
  Catalan: 'ca',
  Corsican: 'co',
  Czech: 'cs',
  Welsh: 'cy',
  Danish: 'da',
  German: 'de',
  'German (Austria)': 'de-AT',
  'German (Switzerland)': 'de-CH',
  'German (Germany)': 'de-DE',
  'German (Liechtenstein)': 'de-LI',
  'German (Luxembourg)': 'de-LU',
  'Lower Sorbian (Germany)': 'dsb',
  Divehi: 'dv',
  Ewe: 'ee',
  Greek: 'el',
  English: 'en',
  'English (Caribbean)': 'en-029',
  'English (Australia)': 'en-AU',
  'English (Belize)': 'en-BZ',
  'English (Canada)': 'en-CA',
  'English (United Kingdom)': 'en-GB',
  'English (Ireland)': 'en-IE',
  'English (India)': 'en-IN',
  'English (Jamaica)': 'en-JM',
  'English (Malaysia)': 'en-MY',
  'English (New Zealand)': 'en-NZ',
  'English (Republic of the Philippines)': 'en-PH',
  'English (Singapore)': 'en-SG',
  'English (Trinidad and Tobago)': 'en-TT',
  'English (United States)': 'en-US',
  'English (South Africa)': 'en-ZA',
  'English (Zimbabwe)': 'en-ZW',
  Esperanto: 'eo',
  Spanish: 'es',
  'Spanish (Argentina)': 'es-AR',
  'Spanish (Bolivia)': 'es-BO',
  'Spanish (Chile)': 'es-CL',
  'Spanish (Colombia)': 'es-CO',
  'Spanish (Costa Rica)': 'es-CR',
  'Spanish (Dominican Republic)': 'es-DO',
  'Spanish (Ecuador)': 'es-EC',
  'Spanish (Spain)': 'es-ES',
  'Spanish (Guatemala)': 'es-GT',
  'Spanish (Honduras)': 'es-HN',
  'Spanish (Mexico)': 'es-MX',
  'Spanish (Nicaragua)': 'es-NI',
  'Spanish (Panama)': 'es-PA',
  'Spanish (Peru)': 'es-PE',
  'Spanish (Puerto Rico)': 'es-PR',
  'Spanish (Paraguay)': 'es-PY',
  'Spanish (El Salvador)': 'es-SV',
  'Spanish (United States)': 'es-US',
  'Spanish (Uruguay)': 'es-UY',
  'Spanish (Venezuela)': 'es-VE',
  Estonian: 'et',
  Basque: 'eu',
  Persian: 'fa',
  Finnish: 'fi',
  Filipino: 'fil',
  Faroese: 'fo',
  French: 'fr',
  'French (Belgium)': 'fr-BE',
  'French (Canada)': 'fr-CA',
  'French (Switzerland)': 'fr-CH',
  'French (France)': 'fr-FR',
  'French (Luxembourg)': 'fr-LU',
  'French (Principality of Monaco)': 'fr-MC',
  Frisian: 'fy',
  Irish: 'ga',
  'Scottish Gaelic': 'gd',
  Galician: 'gl',
  Guarani: 'gn',
  Alsatian: 'gsw',
  Gujarati: 'gu',
  Hausa: 'ha',
  Hebrew: 'he',
  Hindi: 'hi',
  Croatian: 'hr',
  'Croatian (Latin, Bosnia and Herzegovina)': 'hr-BA',
  'Croatian (Croatia)': 'hr-HR',
  'Upper Sorbian (Germany)': 'hsb',
  'Haitian Creole': 'ht',
  Hungarian: 'hu',
  Armenian: 'hy',
  Indonesian: 'id',
  Igbo: 'ig',
  Yi: 'ii',
  Icelandic: 'is',
  Italian: 'it',
  'Italian (Switzerland)': 'it-CH',
  'Italian (Italy)': 'it-IT',
  Inuktitut: 'iu',
  Japanese: 'ja',
  Javanese: 'jv',
  Georgian: 'ka',
  Kongo: 'kg',
  Kikuyu: 'ki',
  Kazakh: 'kk',
  Greenlandic: 'kl',
  Khmer: 'km',
  Kannada: 'kn',
  Korean: 'ko',
  Konkani: 'kok',
  Kanuri: 'kr',
  Kashmiri: 'ks',
  Kyrgyz: 'ky',
  Luxembourgish: 'lb',
  Luganda: 'lg',
  Lingala: 'ln',
  Lao: 'lo',
  Lithuanian: 'lt',
  Latvian: 'lv',
  Malagasy: 'mg',
  Maori: 'mi',
  Macedonian: 'mk',
  Malayalam: 'ml',
  Mongolian: 'mn',
  'Mongolian (Cyrillic, Mongolia)': 'mn-MN',
  'Mongolian (Traditional Mongolian, PRC)': 'mn-Mong-CN',
  Mohawk: 'moh',
  Marathi: 'mr',
  Malay: 'ms',
  'Malay (Brunei Darussalam)': 'ms-BN',
  'Malay (Malaysia)': 'ms-MY',
  Maltese: 'mt',
  'Burmese (Myanmar)': 'my',
  'Norwegian-bn': 'nb',
  'Norwegian, Bokmål (Norway)': 'nb-NO',
  Nepali: 'ne',
  Dutch: 'nl',
  'Dutch (Belgium)': 'nl-BE',
  'Dutch (Netherlands)': 'nl-NL',
  'Norwegian, Nynorsk': 'nn',
  'Norwegian-no': 'no',
  'Northern Sotho': 'nso',
  'Nyanja (Chichewa)': 'ny',
  Occitan: 'oc',
  Oromo: 'om',
  Oriya: 'or',
  Punjabi: 'pa',
  Polish: 'pl',
  Dari: 'prs',
  Pashto: 'ps',
  Portuguese: 'pt',
  'Portuguese (Brazil)': 'pt-BR',
  'Portuguese (Portugal)': 'pt-PT',
  Quechua: 'qu',
  Kiche: 'quc',
  Romansh: 'rm',
  Rundi: 'rn',
  Romanian: 'ro',
  Russian: 'ru',
  Kinyarwanda: 'rw',
  Sanskrit: 'sa',
  Yakut: 'sah',
  Sardinian: 'sc',
  Sindhi: 'sd',
  Sami: 'se',
  Sinhala: 'si',
  Slovak: 'sk',
  Slovenian: 'sl',
  Shona: 'sn',
  Somali: 'so',
  Albanian: 'sq',
  Serbian: 'sr',
  'Serbian (Cyrillic, Bosnia and Herzegovina)': 'sr-Cyrl-BA',
  'Serbian (Cyrillic, Serbia)': 'sr-Cyrl-SP',
  'Serbian (Latin, Bosnia and Herzegovina)': 'sr-Latn-BA',
  'Serbian (Latin, Serbia)': 'sr-Latn-SP',
  Sotho: 'st',
  Sundanese: 'su',
  Swedish: 'sv',
  'Swedish (Finland)': 'sv-FI',
  'Swedish (Sweden)': 'sv-SE',
  Kiswahili: 'sw',
  Syriac: 'syr',
  Tamil: 'ta',
  Telugu: 'te',
  Tajik: 'tg',
  Thai: 'th',
  Tigrinya: 'ti',
  Turkmen: 'tk',
  Tagalog: 'tl',
  Setswana: 'tn',
  Turkish: 'tr',
  Tsonga: 'ts',
  Tatar: 'tt',
  Tamazight: 'tzm',
  Uighur: 'ug',
  Ukrainian: 'uk',
  Urdu: 'ur',
  Uzbek: 'uz',
  'Uzbek (Cyrillic, Uzbekistan)': 'uz-Cyrl-UZ',
  'Uzbek (Latin, Uzbekistan)': 'uz-Latn-UZ',
  Venda: 've',
  Vietnamese: 'vi',
  Wolof: 'wo',
  isiXhosa: 'xh',
  Yoruba: 'yo',
  'Chinese (Peoples Republic of China)': 'zh-CN',
  'Chinese (Simplified)': 'zh-Hans',
  'Chinese (Traditional)': 'zh-Hant',
  'Chinese (Hong Kong S.A.R.)': 'zh-HK',
  'Chinese (Macao S.A.R.)': 'zh-MO',
  'Chinese (Singapore)': 'zh-SG',
  'Chinese (Taiwan)': 'zh-TW',
  isiZulu: 'zu',
}
